apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs01
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: pvnfs01
  nfs:
    path: /data/nfs/pv_nfs01
    server: 192.168.3.206
