apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvalert
  labels:
    type: nfs
spec:
  storageClassName: alertnfs01
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/alert/alert01
    server: 192.168.3.206
