apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvprom
  labels:
    type: nfs
spec:
  storageClassName: promnfs01
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/prom/prom01
    server: 192.168.3.206
