apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: ops
spec:
  storageClassName: grafananfs01
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

