apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: ops
spec:
  storageClassName: promnfs01
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

