apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: ops
spec:
  storageClassName: alertnfs01
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

