apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvstatic
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/static/static01
    server: 192.168.3.206
